### Recuperar todas las películas

GET http://localhost:3000/categories

### Recuperar una película por id
GET http://localhost:3000/categories/57d408608e1f

### Eliminar una pelicula
DELETE http://localhost:3000/categories/57d408608e1f

### Crear una película
POST http://localhost:3000/access
Content-Type: application/json

{ 
   "idusers": "1",
    "idprofiles": "1"
}

### Actualizar una película
PATCH http://localhost:3000/categories/36d7b16c27a4
Content-Type: application/json

{
   "description": "Pruebita",
    "image": "https://www.sensacine.com/peliculas/"
}
